-- Recurring push notification settings and motivational content library
CREATE TABLE public.motivational_content (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  kind text NOT NULL CHECK (kind IN ('quote','encouragement')),
  idx int NOT NULL,
  text text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(kind, idx)
);
GRANT SELECT ON public.motivational_content TO authenticated;
GRANT ALL ON public.motivational_content TO service_role;
ALTER TABLE public.motivational_content ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins manage motivational content"
  ON public.motivational_content FOR ALL TO authenticated
  USING (public.has_role(auth.uid(),'admin')) WITH CHECK (public.has_role(auth.uid(),'admin'));
CREATE POLICY "Authenticated read motivational content"
  ON public.motivational_content FOR SELECT TO authenticated USING (true);

CREATE TABLE public.recurring_push_settings (
  key text PRIMARY KEY,
  label text NOT NULL,
  cadence text NOT NULL CHECK (cadence IN ('daily','hourly')),
  enabled boolean NOT NULL DEFAULT false,
  title text NOT NULL,
  body text NOT NULL DEFAULT '',
  link text NOT NULL DEFAULT '/',
  hour_utc smallint,
  start_hour_utc smallint NOT NULL DEFAULT 8,
  end_hour_utc smallint NOT NULL DEFAULT 22,
  cycles_content text CHECK (cycles_content IN ('quote','encouragement')),
  next_index int NOT NULL DEFAULT 0,
  last_sent_at timestamptz,
  last_sent_slot text,
  sort_order int NOT NULL DEFAULT 100,
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT ON public.recurring_push_settings TO authenticated;
GRANT ALL ON public.recurring_push_settings TO service_role;
ALTER TABLE public.recurring_push_settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins manage recurring push"
  ON public.recurring_push_settings FOR ALL TO authenticated
  USING (public.has_role(auth.uid(),'admin')) WITH CHECK (public.has_role(auth.uid(),'admin'));

CREATE TRIGGER trg_recurring_push_updated
  BEFORE UPDATE ON public.recurring_push_settings
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

INSERT INTO public.recurring_push_settings (key,label,cadence,title,body,link,hour_utc,sort_order) VALUES
('daily_streak_reminder','Daily Streak Reminder','daily','🔥 Keep your streak alive!','Log in today to keep your daily streak going.','/dashboard',9,10),
('login_claim_rewards','Login to Claim Rewards','daily','🎁 Your rewards are waiting','Login now to claim your daily rewards.','/tasks',8,20),
('task_reminder','Daily Tasks','daily','✅ Daily tasks await','Complete today''s tasks and earn tokens.','/tasks',10,30),
('play_virtual','Play Virtual','daily','⚽ Virtual matches are live','Jump into a virtual round and win big.','/virtual',12,40),
('lottery_reminder','Lottery Draw','daily','🎟️ Grab your lottery ticket','Today''s draw is coming up. Buy your tickets now.','/lottery',13,50),
('arcade_reminder','Arcade','daily','🎮 Play the arcade','Spin the wheel and stack tokens in the arcade.','/arcade',15,60),
('spin_reminder','Daily Spin','daily','🎡 Your free spin is ready','Claim your free daily spin now.','/arcade',11,70),
('gift_reward','Gift Reward','daily','🎁 Free gift unlocked','A new gift is ready for you today.','/dashboard',14,80),
('daily_streak_reward','Streak Reward','daily','🔥 Streak reward available','Come collect today''s streak bonus.','/dashboard',20,90),
('place_bet_reminder','Place a Bet','daily','⚽ Matches are heating up','Place your bets before kickoff.','/matches',18,100);

INSERT INTO public.recurring_push_settings (key,label,cadence,title,body,link,start_hour_utc,end_hour_utc,cycles_content,sort_order) VALUES
('word_of_encouragement','Word of Encouragement','hourly','💛 A word for you',' ','/',8,22,'encouragement',110),
('motivational_quote','Motivational Quote','hourly','✨ Daily motivation',' ','/',8,22,'quote',120);

INSERT INTO public.motivational_content (kind, idx, text) VALUES
('quote', 0, 'Success is the sum of small efforts repeated day in and day out.'),
('quote', 1, 'The future depends on what you do today.'),
('quote', 2, 'Do what you can, with what you have, where you are.'),
('quote', 3, 'Believe you can and you''re halfway there.'),
('quote', 4, 'Fortune favors the bold.'),
('quote', 5, 'Little strokes fell great oaks.'),
('quote', 6, 'Fall seven times, stand up eight.'),
('quote', 7, 'Discipline is the bridge between goals and accomplishment.'),
('quote', 8, 'The best way out is always through.'),
('quote', 9, 'Energy and persistence conquer all things.'),
('quote', 10, 'A goal without a plan is just a wish.'),
('quote', 11, 'Winners never quit and quitters never win.'),
('quote', 12, 'Every champion was once a contender that refused to give up.'),
('quote', 13, 'Hard work beats talent when talent doesn''t work hard.'),
('quote', 14, 'Stars can''t shine without darkness.'),
('quote', 15, 'You miss 100% of the shots you don''t take.'),
('quote', 16, 'Great things never came from comfort zones.'),
('quote', 17, 'Dream it. Wish it. Do it.'),
('quote', 18, 'Push yourself, because no one else is going to do it for you.'),
('quote', 19, 'Sometimes later becomes never. Do it now.'),
('quote', 20, 'Wake up with determination. Go to bed with satisfaction.'),
('quote', 21, 'Don''t watch the clock; do what it does. Keep going.'),
('quote', 22, 'The harder you work for something, the greater you''ll feel when you achieve it.'),
('quote', 23, 'Small daily improvements are the key to staggering long-term results.'),
('quote', 24, 'Focus on being productive instead of busy.'),
('quote', 25, 'The way to get started is to quit talking and begin doing.'),
('quote', 26, 'Success is not final; failure is not fatal.'),
('quote', 27, 'Doubt kills more dreams than failure ever will.'),
('quote', 28, 'Your limitation—it''s only your imagination.'),
('quote', 29, 'Great things take time.'),
('quote', 30, 'Don''t stop when you''re tired. Stop when you''re done.'),
('quote', 31, 'The pain you feel today is the strength you feel tomorrow.'),
('quote', 32, 'Setting goals is the first step in turning the invisible into the visible.'),
('quote', 33, 'Action is the foundational key to all success.'),
('quote', 34, 'Motivation gets you going. Discipline keeps you growing.'),
('quote', 35, 'If it doesn''t challenge you, it doesn''t change you.'),
('quote', 36, 'Winners focus on winning. Losers focus on winners.'),
('quote', 37, 'You are never too old to set another goal or dream a new dream.'),
('quote', 38, 'What you do today can improve all your tomorrows.'),
('quote', 39, 'Don''t count the days, make the days count.'),
('quote', 40, 'Opportunities don''t happen. You create them.'),
('quote', 41, 'The secret of getting ahead is getting started.'),
('quote', 42, 'Nothing will work unless you do.'),
('quote', 43, 'Quality is not an act, it is a habit.'),
('quote', 44, 'Whatever you are, be a good one.'),
('quote', 45, 'An investment in knowledge pays the best interest.'),
('quote', 46, 'Well done is better than well said.'),
('quote', 47, 'You are the CEO of your life. Own it.'),
('quote', 48, 'Progress, not perfection.'),
('quote', 49, 'Chase excellence, success will follow.'),
('quote', 50, 'Consistency is the mother of mastery.'),
('quote', 51, 'Bet on yourself. You always were the sure thing.'),
('quote', 52, 'When you feel like quitting, remember why you started.'),
('quote', 53, 'Winners are just losers who tried one more time.'),
('quote', 54, 'Every setback is a setup for a comeback.'),
('quote', 55, 'Play the long game. Life rewards patience.'),
('quote', 56, 'Comfort is the enemy of achievement.'),
('quote', 57, 'Turn your wounds into wisdom.'),
('quote', 58, 'Be so good they can''t ignore you.'),
('quote', 59, 'You don''t find willpower, you create it.'),
('quote', 60, 'Discipline equals freedom.'),
('quote', 61, 'Success loves preparation.'),
('quote', 62, 'The only bad workout is the one that didn''t happen.'),
('quote', 63, 'Do more of what makes you strong.'),
('quote', 64, 'Confidence comes from evidence. Stack the wins.'),
('quote', 65, 'Aim for progress, not applause.'),
('quote', 66, 'You become what you repeatedly do.'),
('quote', 67, 'Your only competition is who you were yesterday.'),
('quote', 68, 'Show up. That''s most of the battle.'),
('quote', 69, 'Excuses don''t burn calories.'),
('quote', 70, 'Winners embrace hard work.'),
('quote', 71, 'The magic you''re looking for is in the work you''re avoiding.'),
('quote', 72, 'Success rarely comes to those who wait.'),
('quote', 73, 'Be relentless in the pursuit of your goals.'),
('quote', 74, 'One day or day one — you decide.'),
('quote', 75, 'Nothing changes if nothing changes.'),
('quote', 76, 'You''ve survived 100% of your worst days.'),
('quote', 77, 'If plan A fails, remember there are 25 more letters.'),
('quote', 78, 'Doing your best is more important than being the best.'),
('quote', 79, 'The dream is free. The hustle is sold separately.'),
('quote', 80, 'Grow through what you go through.'),
('quote', 81, 'Storms make trees take deeper roots.'),
('quote', 82, 'Be stubborn about your goals, flexible about your methods.'),
('quote', 83, 'Difficult roads often lead to beautiful destinations.'),
('quote', 84, 'Trust the process. Trust the timing.'),
('quote', 85, 'Champions are made when nobody''s watching.'),
('quote', 86, 'Speak your goals into existence and then chase them.'),
('quote', 87, 'Slow progress is still progress.'),
('quote', 88, 'Do it scared.'),
('quote', 89, 'Bet on yourself every single day.'),
('quote', 90, 'You don''t need permission to start.'),
('quote', 91, 'Discipline your mind. Master your emotions.'),
('quote', 92, 'Focus is the new IQ.'),
('quote', 93, 'Success is rented and the rent is due every day.'),
('quote', 94, 'You can''t cheat the grind.'),
('quote', 95, 'When it''s hard, keep going anyway.'),
('quote', 96, 'The best time to plant a tree was 20 years ago. The next best time is now.'),
('quote', 97, 'Direction is more important than speed.'),
('quote', 98, 'Small wins compound into big victories.'),
('quote', 99, 'Own your morning. Elevate your life.'),
('encouragement', 0, 'You''ve got this. One step at a time.'),
('encouragement', 1, 'I''m proud of the effort you''re putting in.'),
('encouragement', 2, 'You are stronger than you think.'),
('encouragement', 3, 'Your best is enough. Keep showing up.'),
('encouragement', 4, 'Every step forward counts, even the small ones.'),
('encouragement', 5, 'You are exactly where you need to be.'),
('encouragement', 6, 'Take a breath. You are doing great.'),
('encouragement', 7, 'Believe in yourself the way we believe in you.'),
('encouragement', 8, 'Even on hard days, you''re growing.'),
('encouragement', 9, 'You bring something special to the world.'),
('encouragement', 10, 'Don''t be so hard on yourself today.'),
('encouragement', 11, 'Your feelings are valid. Keep going.'),
('encouragement', 12, 'You matter more than you know.'),
('encouragement', 13, 'You are becoming everything you''re meant to be.'),
('encouragement', 14, 'Give yourself grace. You''re learning.'),
('encouragement', 15, 'Rest is part of the journey, not a break from it.'),
('encouragement', 16, 'You are loved and valued.'),
('encouragement', 17, 'Progress is progress, no matter how slow.'),
('encouragement', 18, 'The sun will rise. So will you.'),
('encouragement', 19, 'Trust yourself. You''ve made it this far.'),
('encouragement', 20, 'You are enough. Right now, as you are.'),
('encouragement', 21, 'Keep your head up, champion.'),
('encouragement', 22, 'Your kindness makes the world brighter.'),
('encouragement', 23, 'Something wonderful is on its way to you.'),
('encouragement', 24, 'You are capable of amazing things.'),
('encouragement', 25, 'Storms don''t last forever.'),
('encouragement', 26, 'Your hard work will pay off.'),
('encouragement', 27, 'You''ve overcome hard things before. You''ll do it again.'),
('encouragement', 28, 'Take it slow. Take it steady. Just don''t stop.'),
('encouragement', 29, 'You deserve every good thing coming your way.'),
('encouragement', 30, 'Be gentle with yourself today.'),
('encouragement', 31, 'You are braver than you believe.'),
('encouragement', 32, 'Your story isn''t over. The best chapters are ahead.'),
('encouragement', 33, 'You are seen. You are heard. You are valued.'),
('encouragement', 34, 'Keep planting seeds. The garden is coming.'),
('encouragement', 35, 'You are doing better than you think.'),
('encouragement', 36, 'You inspire more people than you realize.'),
('encouragement', 37, 'Your light is needed in this world.'),
('encouragement', 38, 'It''s okay to not be okay. It''s not okay to give up.'),
('encouragement', 39, 'You are worthy of love and success.'),
('encouragement', 40, 'Deep breath. New chance.'),
('encouragement', 41, 'Even miracles take a little time.'),
('encouragement', 42, 'You are the author of your next chapter.'),
('encouragement', 43, 'Something great is around the corner.'),
('encouragement', 44, 'You are stronger than any obstacle.'),
('encouragement', 45, 'Your dreams are valid.'),
('encouragement', 46, 'You have survived every hard day so far.'),
('encouragement', 47, 'Keep believing. Keep going.'),
('encouragement', 48, 'There is magic in your persistence.'),
('encouragement', 49, 'You are already a work of art.'),
('encouragement', 50, 'Give yourself credit for how far you''ve come.'),
('encouragement', 51, 'You are loved beyond measure.'),
('encouragement', 52, 'Your smile matters. Wear it.'),
('encouragement', 53, 'You bring warmth wherever you go.'),
('encouragement', 54, 'Never underestimate your ripple effect.'),
('encouragement', 55, 'You are one decision away from a different life.'),
('encouragement', 56, 'Feel the fear and do it anyway.'),
('encouragement', 57, 'You''ve got the strength for this.'),
('encouragement', 58, 'Little by little, a little becomes a lot.'),
('encouragement', 59, 'Your future self is cheering for you.'),
('encouragement', 60, 'Be proud of who you''re becoming.'),
('encouragement', 61, 'You are more resilient than you give yourself credit for.'),
('encouragement', 62, 'Stand tall. You''ve earned it.'),
('encouragement', 63, 'You are the calm in your own storm.'),
('encouragement', 64, 'Give yourself permission to shine.'),
('encouragement', 65, 'You are wonderfully, uniquely made.'),
('encouragement', 66, 'Even slow progress lands you far from the start.'),
('encouragement', 67, 'Every day is a new page.'),
('encouragement', 68, 'You are stronger after every setback.'),
('encouragement', 69, 'Your worth isn''t measured by productivity.'),
('encouragement', 70, 'Kindness looks good on you.'),
('encouragement', 71, 'Take up space. You belong here.'),
('encouragement', 72, 'You are doing enough. You are enough.'),
('encouragement', 73, 'Your effort is noticed, even when quiet.'),
('encouragement', 74, 'You are a warrior in your own right.'),
('encouragement', 75, 'Bloom in your own time.'),
('encouragement', 76, 'Grace over pressure today.'),
('encouragement', 77, 'You are a masterpiece and a work in progress.'),
('encouragement', 78, 'Softness is not weakness.'),
('encouragement', 79, 'Your comeback will be greater than your setback.'),
('encouragement', 80, 'You are gold, even on cloudy days.'),
('encouragement', 81, 'There is a light in you that no one can dim.'),
('encouragement', 82, 'Keep swimming. You''re closer than you think.'),
('encouragement', 83, 'You are the good energy this world needs.'),
('encouragement', 84, 'You are enough — right here, right now.'),
('encouragement', 85, 'Nothing about you is a mistake.'),
('encouragement', 86, 'You are worthy of the space you take.'),
('encouragement', 87, 'Your heart is strong. Your future is bright.'),
('encouragement', 88, 'You are exactly on time.'),
('encouragement', 89, 'Don''t quit before your miracle.'),
('encouragement', 90, 'You are becoming your bravest self.'),
('encouragement', 91, 'Take a moment. Then take another step.'),
('encouragement', 92, 'You bring more joy than you know.'),
('encouragement', 93, 'Everything you need is inside you.'),
('encouragement', 94, 'You are a whole galaxy in yourself.'),
('encouragement', 95, 'Small acts of courage add up.'),
('encouragement', 96, 'You are meant for great things.'),
('encouragement', 97, 'Keep the faith. It''s working.'),
('encouragement', 98, 'You are a beautiful becoming.'),
('encouragement', 99, 'Rise, dear one. The world needs you.');